### ISSUE TITLE
RFC: migrate to use custom tab page

### ISSUE THREAD

**Issue by MaikoTan** [sdwebui-w-horde/sd-webui-stable-horde-worker#10]
## Summary

The extension now has multiple actions that should not be on the settings page, which makes users confused.
I think it is better to have a dedicated tab page for our extension.

## Imagine

Title: Stable Horde

Layout:

```text
---------------------------------------------------------------------
| Current State: Running | Worker Type: Generation | Apply Settings |
|-------------------------------------------------------------------|
| [x] Enable                         |  Current ID: xxxx-xxxxxxxx   |
| [x] Maintainance Mode              |  [x] Show Image              |
| [x] Allow img2img                  |                              |
| [x] Allow inpainting               |                              |
| [x] Allow Unsafe IP Address        |        Current Image         |
|------------------------------------|                              |
|  Model Selection                   |------------------------------|
|------------------------------------|           Prompt             |
|  [x] Anything Diffusion            |                              |
|      Unknown Model                 |                              |
---------------------------------------------------------------------
```

**Comment by yami-no-tusbas** [comment]
I would love that, and can we have a copy of wath is generated too ? Because if it's a good prompt we may want to learn from it later.

**Comment by MaikoTan** [comment]
> I would love that, and can we have a copy of wath is generated too ? Because if it's a good prompt we may want to learn from it later.

Yes, there's an extra PR that add `Save Image` feature to the tab page in #25 that would be merged as soon as possible.
But it will take up massive storage.

**Comment by yami-no-tusbas** [comment]
Good to hear ! I'll wait then.
