### ISSUE TITLE
[Bug]: Unknown sampler k_lms_ka

### ISSUE THREAD

**Issue by Mikroprozessori** [sdwebui-w-horde/sd-webui-stable-horde-worker#117]
### Is there existing issue for this?

- [X] I checked and didn't find similar issue

### Does this happen on the latest commit?

- [X] I have confirmed this happens on the latest commit

### What happened?

while running the extension got this error in the console:

Exception: ERROR: Unknown sampler k_lms_ka
Traceback (most recent call last):
  File "D:\stable-diffusion-webui_v1.9.3\extensions\sd-webui-stable-horde-worker\stable_horde\horde.py", line 198, in run
    await self.handle_request(req)
  File "D:\stable-diffusion-webui_v1.9.3\extensions\sd-webui-stable-horde-worker\stable_horde\horde.py", line 303, in handle_request
    raise Exception(f"ERROR: Unknown sampler {sampler_name}")

### Steps to reproduce

run the extention

### What did you expect to happen?

it would like some advice so I can run the worker without being put into maintenance mode for dropping requests

### Stable Diffusion WebUI Commit SHA

1c0a0c4c26f78c32095ebc7f8af82f5c04fca8c0

### What operating system are you seeing the problem on?

Windows 11 / 10 / 8

### What browsers are you seeing the problem on?

Chrome

**Comment by gabriel20xx** [comment]
I made a pull request on this, see #120.
However, it needs to be approved by a reviewer first.

**Comment by MaikoTan** [comment]
Added by #120
