### ISSUE TITLE
[Bug]: Unknown sampler k_dpmpp_2s_a_ka

### ISSUE THREAD

**Issue by gabriel20xx** [sdwebui-w-horde/sd-webui-stable-horde-worker#118]
### Is there existing issue for this?

- [X] I checked and didn't find similar issue

### Does this happen on the latest commit?

- [X] I have confirmed this happens on the latest commit

### What happened?

Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/extensions/sd-webui-stable-horde-worker/stable_horde/horde.py", line 198, in run
    await self.handle_request(req)
  File "/home/user/stable-diffusion-webui/extensions/sd-webui-stable-horde-worker/stable_horde/horde.py", line 303, in handle_request
    raise Exception(f"ERROR: Unknown sampler {sampler_name}")
Exception: ERROR: Unknown sampler k_dpmpp_2s_a_ka

### What did you expect to happen?

No error

### Stable Diffusion WebUI Commit SHA

463d6a9fe8a4b56a4d69ef3692074c0617428dfd8e8f12f9efe3b1e9a71717ce

### What operating system are you seeing the problem on?

Windows 11 / 10 / 8, Debian / Ubuntu

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by MaikoTan** [comment]
Added by #120

**Comment by Mikroprozessori** [comment]
this bug still remains, I updated evrything and got this:
