### ISSUE TITLE
[Bug]:  Stable Horde hasnt been working for days

### ISSUE THREAD

**Issue by Surferburger** [sdwebui-w-horde/sd-webui-stable-horde-worker#122]
### Is there existing issue for this?

- [X] I checked and didn't find similar issue

### Does this happen on the latest commit?

- [X] I have confirmed this happens on the latest commit

### What happened?

https://aqualxx.github.io/stable-ui/

Its 'Models' have been 'Down' for me for days, So i havent been able to generate anything. Is this a bug? Is it updates being performed? Can someone help me pls? Ty.

I dont know where the Stable Diffusion WebUI Commit SHA is on that website.

### What did you expect to happen?

![---------](https://github.com/sdwebui-w-horde/sd-webui-stable-horde-worker/assets/170055572/0ca88a61-e75f-4453-9bc3-e691e7a5999b)

### Stable Diffusion WebUI Commit SHA

I cant find it because its made so hard to find

### What operating system are you seeing the problem on?

Windows 11 / 10 / 8

### What browsers are you seeing the problem on?

Firefox

### Additional information

![---------](https://github.com/sdwebui-w-horde/sd-webui-stable-horde-worker/assets/170055572/982c5c4e-575d-45c4-84f3-5461b9778c74)

**Comment by gabriel20xx** [comment]
I think your posting your issue in the wrong repository. This repository is the Stable Horde Worker plugin / extension of the A1111 Stable Diffusion UI.

**Comment by Surferburger** [comment]
> I think your posting your issue in the wrong repository. This repository is the Stable Horde Worker plugin / extension of the A1111 Stable Diffusion WebUI.

.. It is made, Soo, HARD to get resolutions on that website, I posted. And to find, Help, From, Someone there. It is normal, For people to ask others, For assistance with things. Whether its on Discord, Or other places.

**Comment by gabriel20xx** [comment]
It wasn't my intention to offend you. I just tried to help 🙂

**Comment by Surferburger** [comment]
> It wasn't my intention to offend you. I just tried to help 🙂 I can understand your frustration, it is sometimes hard to get help or responses even for me

.. You didnt offend me, Honestly. They just werent being very friendly in discord whenever i (Thought) Id found the appropriate-server for this place. Its how many always treat some of us in the world. .

**Comment by gabriel20xx** [comment]
Issue is no longer present
