### ISSUE TITLE
About Adding License

### ISSUE THREAD

**Issue by MaikoTan** [sdwebui-w-horde/sd-webui-stable-horde-worker#18]
## Summary

It would be better to have a license for this repository.

But since we [have copied images from natali](https://github.com/sdwebui-w-horde/sd-webui-stable-horde-worker/issues/4) which has an **AGPL license**, I am not sure whether or not should we use the same license as well.

Personally I would prefer MIT license though.

**Comment by db0** [comment]
You don't need the images from nataili. While I generally suggest people use AGPL3 to avoid getting screwed by corpos, feel free to use MIT

**Comment by MaikoTan** [comment]
> You don't need the images from nataili. While I generally suggest people use AGPL3 to avoid getting screwed by corpos, feel free to use MIT

It seems like that I could make those "censored images" myself so then we don't need to depend on nataili's.

As the license problem, it looks like AGPL is not bad for us as well. cc @MirrorCY 

I would continue tracking on this when I were fully recovered from COVID. 😂

**Comment by db0** [comment]
I made those images. I hereby allow you to use those as CC0 :D
