### ISSUE TITLE
validation error: ldsr cached

### ISSUE THREAD

**Issue by ClashSAN** [sdwebui-w-horde/sd-webui-stable-horde-worker#20]
raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for Options
response -> ldsr_cached
  value is not None (type=type_error.not_none)

**Comment by MaikoTan** [comment]
:tada: Thanks for your first issue! :tada:


Can you provide more logs and details about the error message, also the configuration you're using?
It is not clear that I could not investigate what is wrong.

Thanks!

**Comment by ClashSAN** [comment]
Somehow, this issue resolved itself. I just reinstalled everything.
