### ISSUE TITLE
How does this work ?

### ISSUE THREAD

**Issue by yami-no-tusbas** [sdwebui-w-horde/sd-webui-stable-horde-worker#29]
I installed [stable diffusion webui stable horde](https://github.com/natanjunges/stable-diffusion-webui-stable-horde) and created an account, inputed my key, but nothing is happenning. How do I know if the client is connected, receiving work or anything ?

All I got is : ![firefox_23-01-24 15-36(242)](https://user-images.githubusercontent.com/3921598/214323214-e73c820c-f2e1-4888-94af-df874f9afbdc.png)

I don't need to use the horde to generate and wanted my pc to be used for the horde. Do I need  to install the hord software in addition to automatic's webui ?

**Comment by yami-no-tusbas** [comment]
I'm dumb... it's the worker I need !

**Comment by MaikoTan** [comment]
Yeah lol.

The image you posted is the `stable horde client` extension, it is not the extension of ours that is named `stable horde worker bridge`.

Our extension is still working in progress, so it might not be stable for production use. That is why it is not in the extension list of AUTOMATIC1111's webui.

Thanks for trying our first baby extension!
