### ISSUE TITLE
Feature: model switching

### ISSUE THREAD

**Issue by MaikoTan** [sdwebui-w-horde/sd-webui-stable-horde-worker#3]
## Summary

Currently users should switch the model manually, which would lead to error.

### Solution

Support auto switching models from payload, based on #2 , UI based on #10

**Comment by rafx85** [comment]
I would also have that feature, auto model switching, instead of setting and user can generate what you have set only.

**Comment by theUpsider** [comment]
Im a new contributor, experienced python developer thou. Just tinkering and getting familiar with the codebase. When I feel confident enough I'll take on this issue.

**Comment by theUpsider** [comment]
Ok it works smooth as a charm. I will clean up the code etc. and make a pull request.

**Comment by theUpsider** [comment]
Anyone got an idea how to display the loading time while it calculates the md5 hash? This really takes quite a time and the models are not ready before it finished.
