### ISSUE TITLE
Need to know

### ISSUE THREAD

**Issue by yami-no-tusbas** [sdwebui-w-horde/sd-webui-stable-horde-worker#31]
How can I see what is generated ? I see the text in my console, but the images are nowere on my computer, how can I see them ? It would be usefull to report a user generating bad things for exxemple.

**Comment by MaikoTan** [comment]
Hello @yami-no-tusbas !

I have merged the UI changes in #13 into the master branch. You could pull the latest version of our extension now to experience it.
I'll add "blacklist" feature in the next days, if I am not very busy lol.

**Comment by yami-no-tusbas** [comment]
Yeah no problem thanks ! This will be something very usefull in the late game !

**Comment by yami-no-tusbas** [comment]
Just tested, It's GREAT ! Now I can be relief ! Next thing is a report form xD But it's for the future, I can always mail them, but i have no trace of the tast, I can see in the UI a task with some kind of ID, but ine the image itseflt there is no sign of it, can it be added to the generation information ? So if I need to report I send the image and with the metadata they can trace the user.
