### ISSUE TITLE
[Bug]: hash changes - model not found on StableHorde

### ISSUE THREAD

**Issue by ClashSAN** [sdwebui-w-horde/sd-webui-stable-horde-worker#55]
### Is there existing issue for this?

- [X] I checked and didn't find similar issue

### Does this happen on the latest commit?

- [X] I have confirmed this happens on the latest commit

### What happened?

new model hashing system not recognized by SDHordeWorker. no errors in terminal

### Steps to reproduce

on cc8c9b7 of webui,

infobox shows: Current model Anything-V3.0-pruned.ckpt [543bcbc212] not found on StableHorde

using da0e8e8fe9901fb1d724e85b3b7203542cc3d946 of this extension

using an older version of webui - 9cfd10cde (Jan 11) still works with this model, on current extension version

### What did you expect to happen?

connection success

### Stable Diffusion WebUI Commit SHA

cc8c9b7

### What operating system are you seeing the problem on?

Windows 11 / 10 / 8

### What browsers are you seeing the problem on?

Firefox

**Comment by MaikoTan** [comment]
I found that the Anything Diffusion that Stable Horde using is updated to the [V4.5 version](https://huggingface.co/andite/anything-v4.0), try to download the new one with this link: https://huggingface.co/Airic/Anything-V4.5/resolve/main/Anything-v4.5-pruned-mergedVae.ckpt

This turns out it might be time to implement the model selection feature with auto-downloading. Sorry!

**Comment by ClashSAN** [comment]
hmm, that's right, the model was removed by owner on huggingface. But still, somehow, I was able to server 3.0 on an older version? well that's interesting, 4.0 is not the same thing right?

**Comment by MaikoTan** [comment]
Yeah, I found that too.
The problem is that we "download" the model references database (https://raw.githubusercontent.com/Sygil-Dev/nataili-model-reference/main/db.json) to the local disk, but didn't update it after that anymore.

I would fix it in the next few days.

**Comment by MaikoTan** [comment]
(Yep, the stable horde server side doesn't even care about what model you are using, it is all given to the worker bridge client...)

**Comment by ClashSAN** [comment]
I'll try that 4.5 version btw
I just installed fresh so, good to test

**Comment by MaikoTan** [comment]
Yep, so a temporary solution is to delete the `stablehorde_supported_models.json` and then re-launch the webui.

**Comment by ClashSAN** [comment]
works!
had to get new api key since i was put into maintenance mode very often. I disable processing and some other img2img and inpaint modes and I think it was not processing these properly (since I used an old webui version)

**Comment by MaikoTan** [comment]
> I had to get new api key since i was put into maintenance mode very often. I disable processing and some other img2img and inpaint modes and I think it was not processing these properly (since I used an old webui version)

Oh, you don't need to.
Some Horde UI like https://aqualxx.github.io/stable-ui/ allows you to turn off/on the maintenance mode.

And I would implement the maintenance mode switch on our side as soon as possible.

**Comment by DmitriyPekar** [comment]
does not work with any models, I deleted the file responsible for the list of models, the latest version of webui

**Comment by MaikoTan** [comment]
> does not work with any models, I deleted the file responsible for the list of models, the latest version of webui

what model are you using?

**Comment by DmitriyPekar** [comment]
> > does not work with all models, I deleted the file responsible for the list of models, the latest version of webui > > what model do you use?

DreamShaper

**Comment by MaikoTan** [comment]
> DreamShaper

stable horde updated their DeeamSharper model as well as Anything, you should download this one...
https://huggingface.co/Airic/Dreamshaper_33-vae/resolve/main/dreamshaper_33-inclVae.ckpt

So it is the time to implement the model downloading feature. 😭

**Comment by DmitriyPekar** [comment]
> > DreamShaper
> 
> stable horde updated their DeeamSharper model as well as Anything, you should download this one... https://huggingface.co/Airic/Dreamshaper_33-vae/resolve/main/dreamshaper_33-inclVae.ckpt
> 
> So it is the time to implement the model downloading feature. 😭

model checkpoint not found

**Comment by MaikoTan** [comment]
> > > DreamShaper
> > 
> > 
> > stable horde updated their DeeamSharper model as well as Anything, you should download this one... [huggingface.co/Airic/Dreamshaper_33-vae/resolve/main/dreamshaper_33-inclVae.ckpt](https://huggingface.co/Airic/Dreamshaper_33-vae/resolve/main/dreamshaper_33-inclVae.ckpt)
> > So it is the time to implement the model downloading feature. 😭
> 
> model checkpoint not found

Yep, I found that too.
But I still don't know what is the problem here. I would investigating this issue as soon as possible.
