### ISSUE TITLE
[Bug]: Sampler problem ?

### ISSUE THREAD

**Issue by yami-no-tusbas** [sdwebui-w-horde/sd-webui-stable-horde-worker#61]
### Is there existing issue for this?

- [X] I checked and didn't find similar issue

### Does this happen on the latest commit?

- [X] I have confirmed this happens on the latest commit

### What happened?

It was running fast yesterday, since the update of automatic's 1111 GUI it's dead sending error :

```
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\extensions\sd-webui-stable-horde-worker\stable_horde\horde.py", line 153, in run
    await self.handle_request(req)
  File "C:\stable-diffusion-webui\extensions\sd-webui-stable-horde-worker\stable_horde\horde.py", line 221, in handle_request
    self.patch_sampler_names()
  File "C:\stable-diffusion-webui\extensions\sd-webui-stable-horde-worker\stable_horde\horde.py", line 164, in patch_sampler_names
    from modules.sd_samplers import KDiffusionSampler, SamplerData
ImportError: cannot import name 'KDiffusionSampler' from 'modules.sd_samplers' (C:\stable-diffusion-webui\modules\sd_samplers.py)
```

To be sure I re-installed hord worker but nothing change. This may have  to do with recent update on automatic1111 side.

### Steps to reproduce

Install the extension, configure it, and watch the error popping for each request.

### What did you expect to happen?

Nothing special, just the extension working like yesterday.

### Stable Diffusion WebUI Commit SHA

ab059b6e4863eaa5e118a2043192584e6df51ed4

### What operating system are you seeing the problem on?

Windows 11 / 10 / 8

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

**Comment by MaikoTan** [comment]
It looks like the a1111 webui changed the internal API recently. I will take a look and fix it as soon as possible.

Thanks for reporting!

**Comment by MaikoTan** [comment]
It is fixed, please update to the latest version.
