### ISSUE TITLE
[Bug]: Img2Img seems to ignore source image

### ISSUE THREAD

**Issue by db0** [sdwebui-w-horde/sd-webui-stable-horde-worker#65]
### Is there existing issue for this?

- [X] I checked and didn't find similar issue

### Does this happen on the latest commit?

- [X] I have confirmed this happens on the latest commit

### What happened?

Source
![image](https://user-images.githubusercontent.com/296513/219864142-249d2cef-2e63-4216-8b65-e46fbec0bda3.png)
AI Horde Worker | Webui
![image](https://user-images.githubusercontent.com/296513/219864151-686e3aec-f944-4cb4-aa41-4193b886f982.png)

It seems this worker seems to ignore the source image in img2img. I am going to have to disable sending img2img to these workers until this is fixed.

### Steps to reproduce

generate an img2img on the horde and send to the webui worker

### What did you expect to happen?

The source image should be used

### Stable Diffusion WebUI Commit SHA

All

### What operating system are you seeing the problem on?

Other

### What browsers are you seeing the problem on?

Other

**Comment by MaikoTan** [comment]
Okay, I'll take a look on this bug and investigate how is it going on. Sorry.

**Comment by MaikoTan** [comment]
@db0 It should work with the latest version, but I don't know how to test it since you disabled the img2img feature on the AI-Horde side.

**Comment by db0** [comment]
I'll re-enable soon then

**Comment by db0** [comment]
Also can you make it able to handle downloading the source image from r2, as that is the new approach. The source image and source mask key would be as r2 url

**Comment by MaikoTan** [comment]
> Also can you make it able to handle downloading the source image from r2, as that is the new approach. The source image and source mask key would be as r2 url

I planned to implement this feature in #70 and then bump the bridge version after that. So it looks like I could mark the `r2 source` feature as version 3 and then `hires fix`/`clip skip` as version 4.
