### ISSUE TITLE
[Feature]: Add hires_fix and clip_skip feature

### ISSUE THREAD

**Issue by MaikoTan** [sdwebui-w-horde/sd-webui-stable-horde-worker#69]
### Is there existing issue for this?

- [X] I didn't find similar issue, also checked the latest commit.

### Feature Description

Stable Horde side produced these feature that sd-webui could support with small changes.

Should also bump the version to 3 as well.

### Proposed Solution

Add hires_fix parameters in the processing progress, and change clip_skip on the fly.

### Additional Information

https://github.com/db0/AI-Horde/pull/172

**Comment by theUpsider** [comment]
Please update the readme.md to include the Clip skip feature :)

**Comment by MaikoTan** [comment]
> Please update the readme.md to include the Clip skip feature :)

Yes, I would change the readme.md when I implementing the hires_fix feature as well.
