### ISSUE TITLE
[Bug]: Sygil-Dev no longer the source for nataili 

### ISSUE THREAD

**Issue by tazlin** [sdwebui-w-horde/sd-webui-stable-horde-worker#74]
### Is there existing issue for this?

- [X] I checked and didn't find similar issue

### Does this happen on the latest commit?

- [X] I have confirmed this happens on the latest commit

### What happened?

https://github.com/Sygil-Dev/* is no longer the canonical repo for nataili or related projects.

Please refer to the repos found at https://github.com/db0/nataili and https://github.com/db0/AI-Horde-image-model-reference for now. 

### What did you expect to happen?

See above.

### Stable Diffusion WebUI Commit SHA

0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8

### What operating system are you seeing the problem on?

Other

### What browsers are you seeing the problem on?

Other

### Additional information

Please come to the official discord or message db0 for more information.

**Comment by tazlin** [comment]
To be clear- the old repos are gone, and this extensions reliance on them is the chief concern with this bug report.

**Comment by theUpsider** [comment]
I targeted that problem in my pull request as well, as it was just one line of code.

**Comment by MaikoTan** [comment]
I am going to fix this bug first, @theUpsider can you split this "one line fixing" from #75 into a new PR and then we could make it fixed immediately?

**Comment by theUpsider** [comment]
Sorry it was night-time for me. Just woke up and did the pull request.

**Comment by MaikoTan** [comment]
> Sorry it was night-time for me. Just woke up and did the pull request.

Thanks for the contribution, it is okay.

**Comment by MaikoTan** [comment]
Would it be better to fetch models from https://stablehorde.net/api/v2/status/models instead of the json file from github?

**Comment by theUpsider** [comment]
Then we need to change the code and not calculate the md5 checksum anymore, since the link you provided doesn't include hashes. Currently I calculate the checksum and compare the hash to the model in the URL. In my opinion this contributes to better quality of Stable horde since people can't choose different models that easily. Ofc they could simply modify the code. But that's a minority that knows this works.

**Comment by MaikoTan** [comment]
> Then we need to change the code and not calculate the md5 checksum anymore, since the link you provided doesn't include hashes. Currently I calculate the checksum and compare the hash to the model in the URL. In my opinion this contributes to better quality of Stable horde since people can't choose different models that easily. Ofc they could simply modify the code. But that's a minority that knows this works.

You're right, never mind it.
