### ISSUE TITLE
[Bug]: "Save Images" saves correctly but always loads as false in the UI but works anyway

### ISSUE THREAD

**Issue by axemaster** [sdwebui-w-horde/sd-webui-stable-horde-worker#88]
### Is there existing issue for this?

- [X] I checked and didn't find similar issue

### Does this happen on the latest commit?

- [X] I have confirmed this happens on the latest commit

### What happened?

I check off Save Images. I Apply Settings. I look at the config.json. It is correct. The next time I start A1111 the checkbox is not checked.  I look at the config again. It is correct. I look at the file system and verify the The worker is saving images. It is. I Apply Settings. I look at the config. It saved the setting as false (as indicated in the UI but not reflecting the current behavior).

Current work around: I check it off every time I start up because I don't want it false in the config.

### What did you expect to happen?

UI is correct

### Stable Diffusion WebUI Commit SHA

https://google.com/search?q=b4391b7978d973427a4a2a3ed0e67b18ebe34e213904575043d6c9faec75c22d

### What operating system are you seeing the problem on?

macOS

### What browsers are you seeing the problem on?

Other

### Additional information

Tested in both Safari and Chrome.

**Comment by thatjimupnorth** [comment]
Mine doesn't save anything at all. Someone on the Discord said it's not supposed to be can with the Automatic1111 extension. Is this now broken or am I missing something? I'm just interested to see what other users are prompting. It's running jobs and in the CLI it's saying everything is working properly, but the Save Images and Show Images in the 1111 tab don't refresh and there's nothing being saved to the output directory.

**Comment by axemaster** [comment]
> ...there's nothing being saved to the output directory.

Update the config file and change it there. Don't press Apply in the extension UI because it overwrites it. Try it, might work.

Here is the vim command but use whatever editor you wish to edit the file.

`$vim extensions/sd-webui-stable-horde-worker/config.json
`

```
{
  "enabled": true,
  "allow_img2img": true,
  "allow_painting": true,
  "allow_unsafe_ipaddr": false,
  "allow_post_processing": false,
  "show_image_preview": false,
  "save_images": true,

```

**Comment by axemaster** [comment]
PS: The images are save in this directory

`stable-diffusion-webui/horde`

**Comment by MaikoTan** [comment]
It seems there are bugs when loading and saving the config.json file, I would investigate it as soon as possible. Thanks for the report.
