### ISSUE TITLE
[Bug]: NSFW filter censors everything

### ISSUE THREAD

**Issue by Kryptortio** [sdwebui-w-horde/sd-webui-stable-horde-worker#91]
### Is there existing issue for this?

- [X] I checked and didn't find similar issue

### Does this happen on the latest commit?

- [X] I have confirmed this happens on the latest commit

### What happened?

Changed to not allow NSFW but then everything gets censored. 

For example this prompt `easter bunny with a easter egg with the Bitcoin logo, ((realistic)), ((RTX)), highres, ((photorealistic)), dreamlikeart` got censored with the black "NSFW content detected and the client requested it to be blocked".

I have tried several images now but everything gets blocked. I get the black censor sometimes when NSFW is allowed as well but I assume that's because the client actually requested it.

### What did you expect to happen?

Not accept prompts from stable horde with NSFW words in them.

### Stable Diffusion WebUI Commit SHA

22bcc7be428c94e9408f589966c2040187245d81

### What operating system are you seeing the problem on?

Windows 11 / 10 / 8

### What browsers are you seeing the problem on?

Firefox

### Additional information

sd-webui-stable-horde-worker commit hash a3e67b51f706fcca7004656b54eee296a748d8a4

Only using standard extensions and sd-webui-controlnet.

**Comment by Kryptortio** [comment]
Tried installing the stable-diffusion-webui-nsfw-censor extension and that one works fine so I guess it's not a dependency issue. I thought that maybe I had to install `CompVis/stable-diffusion-safety-checker` somehow but looks like it's available.

**Comment by Kryptortio** [comment]
If anyone needs a workaround for this, open the file `\stable-diffusion-webui\extensions\sd-webui-stable-horde-worker\stable_horde\job.py` and go to [line 207](https://github.com/sdwebui-w-horde/sd-webui-stable-horde-worker/blob/a3e67b51f706fcca7004656b54eee296a748d8a4/stable_horde/job.py#L207), there you can add some words to the blacklist. E.g. `"blacklist": ["nude","naked"]` that will stop a lot of NSFW requests and you can keep adding words if you want.

**Comment by ivucica** [comment]
Would it make sense to move this into `StableHordeConfig` and expose it in the configuration UI?

**Comment by Maeyanie** [comment]
I can confirm the filter is blocking stuff which isn't actually NSFW. To test it I modified my copy to save the actual image to my local drive when submitting a censored image, and this was one example of an image which got blocked:
![00052-73927112](https://github.com/sdwebui-w-horde/sd-webui-stable-horde-worker/assets/206142/cc935649-64d6-4ed6-ba53-841907b00d08)
