### ISSUE TITLE
[Bug]: Receiving no jobs

### ISSUE THREAD

**Issue by axemaster** [sdwebui-w-horde/sd-webui-stable-horde-worker#94]
### Is there existing issue for this?

- [X] I checked and didn't find similar issue

### Does this happen on the latest commit?

- [X] I have confirmed this happens on the latest commit

### What happened?

Steady jobs up to yesterday. None today. Posted issue to stable UI GitHub, they said it's working fine and suggesting the issue is use of an out of date API. I have not way to test this.

Latest commit.

### Steps to reproduce

Run A1111 with ext.

### What did you expect to happen?

It works.

### Stable Diffusion WebUI Commit SHA

latest I update before every run

### What operating system are you seeing the problem on?

macOS

### What browsers are you seeing the problem on?

Other

**Comment by axemaster** [comment]
Official worker dev says they can't support this ext so bumping this issue.

**Comment by Kryptortio** [comment]
Check the console if you are getting the same error as this https://github.com/sdwebui-w-horde/sd-webui-stable-horde-worker/issues/95

**Comment by axemaster** [comment]
starting working. don't know why. guessing a fix on horde server-side.
